from CRABClient.UserUtilities import config

config = config()

config.General.requestName = 'ST_tW_top_UL18_customNanoAOD'
config.General.workArea = 'crab_projects'
config.General.transferOutputs = True
config.General.transferLogs = True

config.JobType.pluginName = 'Analysis'
config.JobType.psetName = 'NANO.py'          # generated by cmsDriver --no_exec
config.JobType.outputFiles = ['nano.root']   # must match --fileout in cmsDriver

config.Data.inputDataset = '/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
config.Data.inputDBS = 'global'
config.Data.splitting = 'FileBased'
config.Data.unitsPerJob = 1                  # one input MiniAOD file per job
config.Data.publication = False

config.Data.outLFNDirBase = '/store/user/<your_username>/customNanoAOD/UL18/'
config.Data.outputDatasetTag = 'ST_tW_top_UL18_customNanoAOD'

config.Site.storageSite = 'T3_US_FNALLPC'
